core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produto/', include(('produto.urls', 'produto'), namespace='produto')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('empresa/', include(('empresa.urls', 'empresa'), namespace='empresa')),
    path('pacotes/', include(('pacotes.urls', 'pacotes'), namespace='pacotes')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from .views import *
from django.contrib import admin
from django.urls import path
app_name='produto'
urlpatterns = [
    path('cadastro-produto/',cad_prod,name='cad_prod'),
    path('cadastro-preco/',cad_preco,name='cad-preco'),
    path('search-product/',busca_prod,name='busca-produto'),
    path('secoes/<str:v>/',secoes,name='secoes'),
    path('lista-produtos/',listagem,name='lista-produtos'),
    path('edita-prod/<int:id>/',template_altera,name='altera-dados'),
    path('desabilitado/ ',upd_status,name='desabilita-dado'),
    path('detalhes/<str:titulo>/<int:id>/',detalhes,name='detalhes'),
    path('relatorio/',generate_report, name='relatorio'),
    ]

produto/models.py
from django.db import models
import sys
sys.path.append("")
from empresa.models import *
class secao(models.Model):
    nome_secao=models.CharField(max_length=50)
    def __str__(self):
        return self.nome_secao
class preco(models.Model):
    valor=models.FloatField(null=True)
    def __str__(self):
        return str(self.valor)
class produtos(models.Model):
    nome_produto=models.CharField(max_length=100)
    secao=models.ForeignKey(secao,on_delete=models.CASCADE,verbose_name='Seção')
    imagem=models.ImageField(upload_to='media')
    empresa=models.ForeignKey(Empresa, on_delete=models.CASCADE, null=True)
    status=models.CharField(max_length=2,default='1', null=True)
    preco=models.ForeignKey(preco, on_delete=models.CASCADE, null=True)
    carousel=models.CharField(max_length=2, default='0')
    def __str__(self) -> str:
        return self.nome_produto
class relatorio(models.Model):
    produto=models.ForeignKey(produtos,on_delete=models.CASCADE, default=None)
    data_busca=models.DateField(default=None)
    def __str__(self):
        return self.produto.nome_produto

produto/forms.py
from django import forms
from produto.models import produtos,preco

class ProdutoForm(forms.ModelForm):
    class Meta:
        model=produtos
        fields='__all__'
        widgets={
            'nome_produto':forms.TextInput(attrs={
                'class':'campo','placeholder':'Nome do produto',}),
            'secao':forms.Select(attrs={ 'class': 'campo'}),
            'preco':forms.Select(attrs={'class':'campo','placeholder':'Preço do produto'}),
            'imagem':forms.FileInput(attrs={ 'class': 'campo'}),
            'empresa':forms.Select(attrs={'class': 'campo'}),
            'status':forms.TextInput(attrs={'value':'1', 'readonly':'readonly', 'style':'display:none;'}),
            'carousel':forms.RadioSelect(attrs={},choices=[('1','Sim'),('0','Não')])
        }
class PrecoForm(forms.ModelForm):
    class Meta:
        model=preco
        fields='__all__'
        widgets={
            'valor':forms.NumberInput(attrs={
                'class':'campo','placeholder':'Valor do Preço','style':'margin-top:0;'})
        }

produto/views.py
import os
from django.shortcuts import render,redirect
from django.templatetags.static import static
import io
from reportlab.lib.pagesizes import letter
from django.http import HttpResponse
from datetime import date
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle,Image
from core import settings
from produto.forms import ProdutoForm,PrecoForm
from .models import *
from django.shortcuts import get_object_or_404
import sys
sys.path.append("")
from produto.models import *
from empresa.models import *
from accounts.models import *
from .models import preco,secao
from django.contrib.auth.decorators import login_required
import imghdr

@login_required(login_url='accounts:login')
def cad_prod(request):
    data={}
    data['title']='Cadastro de Produtos'
    if(request.POST):
        data['form']=ProdutoForm(request.POST, request.FILES)
        form=data['form']
        if(data['form'].is_valid()):
            nome=Empresa.objects.get(id=request.POST.get('empresa'))
            quant=nome.quant_prod
            print(nome.pacote)
            r1=Pacote.objects.get(nome=nome.pacote)
            pac=r1.quant_prod
            if(quant<pac):
                quant+=1
                teste=Empresa.objects.filter(nome_empresa=nome).update(quant_prod=quant)
                produto = data['form'].save(commit=False)
                img = request.FILES
                dados_img = imghdr.what(img['imagem'])
                if dados_img == 'png' or dados_img == 'jpeg' or dados_img =='jpg' or dados_img =='webp':
                    
                    data['form'].save()
                    data['msg'] = 'Produto Cadastrado com Sucesso!'
                    data['class'] = 'alert-success'''
                else:
                    data['msg'] = 'Formato de imagem não suportado.'
                    data['class'] = 'alert-danger'''
            elif(quant>=pac):
                data['msg'] = 'Limite do pacote atingido.'
                data['class'] = 'alert-danger'''
        else:
            data['msg'] = 'Formulário inválido.'
            data['class'] = 'alert-danger'''
    else:
        data['form'] = ProdutoForm()
        #data['form']=ProdutoForm()
        data['formpreco']=PrecoForm()
    data['link_form']="{% url 'accounts:index'%}"
    data['nome']='Voltar'
    data['titulo']='Cadastro Produtos'
    return render(request,'../../produto/templates/cadastro_prod.html',data)
@login_required(login_url='accounts:login')
def cad_preco(request):
    data={}
    data['title']='Cadastro de Produtos'
    if(request.POST):
        data['formpreco']=PrecoForm(request.POST)
        precos=request.POST.get('valor')
        precos=preco.objects.filter(valor=precos)
        if(len(precos)==0):
            teste=data['formpreco'].save()
            if(teste):
                data['msg'] = 'Preço Cadastrado com Sucesso!'
                data['class'] = 'alert-success'''
            else:
                data['msg'] = 'Formulário inválido.'
                data['class'] = 'alert-danger'''
        elif(len(precos)>0):
            data['msg'] = 'Este preço já existe.'
            data['class'] = 'alert-danger'''

    data['form']=ProdutoForm()
    data['formpreco']=PrecoForm()
    data['link_form']="{% url 'accounts:index'%}"
    data['nome']='Voltar'
    data['titulo']='Cadastro Produtos'
    return render(request,'../../produto/templates/cadastro_prod.html',data)

def busca_prod(request):
    data = {}
    data['title'] = 'Cadastro de empresas'
    data['link_form'] = '123'
    data['title'] = 'Pesquisa'
    data['titulo'] = 'Cadastro Empresa'
    busca = request.POST.get('search')
    
    data['produtos'] = produtos.objects.raw(
        "SELECT produto.id, produto.nome_produto, secao.nome_secao, empresa.nome_empresa, "
        "MAX(preco.valor) AS maior_preco, MIN(preco.valor) AS menor_preco, produto.imagem "
        "FROM produto_produtos AS produto "
        "INNER JOIN produto_secao AS secao ON produto.secao_id = secao.id "
        "INNER JOIN empresa_empresa AS empresa ON produto.empresa_id = empresa.id "
        "INNER JOIN produto_preco AS preco ON produto.preco_id = preco.id "
        "WHERE produto.nome_produto LIKE %s AND produto.status = 1 "
        "GROUP BY produto.nome_produto",
        ['%' + busca + '%']
    )
    return render(request, '../../produto/templates/lista_produtos.html', data)
def secoes(request, v):
    data = {}
    data['title'] = 'Cadastro de empresas'
    data['link_form'] = '123'
    data['title'] = 'Pesquisa'
    data['titulo'] = 'Cadastro Empresa'
    busca = secao.objects.get(nome_secao=v)
    print(busca)
    data['produtos'] = produtos.objects.raw(
        "SELECT produto.id, produto.nome_produto, secao.nome_secao, empresa.nome_empresa, "
        "MAX(preco.valor) AS maior_preco, MIN(preco.valor) AS menor_preco, produto.imagem "
        "FROM produto_produtos AS produto "
        "INNER JOIN produto_secao AS secao ON produto.secao_id = secao.id "
        "INNER JOIN empresa_empresa AS empresa ON produto.empresa_id = empresa.id "
        "INNER JOIN produto_preco AS preco ON produto.preco_id = preco.id "
        "WHERE secao.nome_secao LIKE %s AND produto.status = 1 "
        "GROUP BY produto.nome_produto",
        ['%' + busca.nome_secao + '%']
    )
    return render(request, '../../produto/templates/lista_produtos.html', data)

def listagem(request):
    data={}
    data['adm']='ok'
    data['btn']='Desativar'
    data['msn']='desativar'
    data['t1']='s'
    data['produtos']=produtos.objects.filter(status=1).order_by('nome_produto')
    return render(request, '../../produto/templates/lista_adm.html',data)
@login_required(login_url='accounts:login')
def upd_status(request):
    data={}
    data['btn']='Desativar'
    id=request.POST.get('id')
    desct=produtos.objects.filter(id=id).update(status=0)
    
    return redirect('produto:lista-produtos')
@login_required(login_url='accounts:login')
def template_altera(request,id):
    data={}
    query=produtos.objects.get(id=id)
    data['form']=ProdutoForm(instance=query)
    data['formpreco']=PrecoForm()
    if(request.POST):
        form=ProdutoForm(request.POST)
        if(form.is_valid()):
            sv=form.save()
            if(sv):
                data['msg'] = 'Produto Alterado com sucesso!'
                data['class'] = 'alert-success'''
            else:
                data['msg'] = 'Produto Não Alterado.'
                data['class'] = 'alert-danger'''
        elif(not form.is_valid()):
            data['msg'] = "O produto não foi alterado \n Formulário inválido ." 
            data['class'] = 'alert-danger'''
    data['id']=id
    return render(request,'../../produto/templates/edita_prod.html',data)
def detalhes(request,titulo,id):
    data = {}
    data['title'] = 'Cadastro de empresas'
    produto = get_object_or_404(produtos, pk=id)
    rel = relatorio(produto=produto, data_busca=date.today())
    rel.save()
    data['link_form'] = '123'
    data['title'] = 'Pesquisa'
    data['titulo'] = 'Cadastro Empresa'
    data['empresas']=produtos.objects.filter(nome_produto=titulo)
    data['produto']=get_object_or_404(produtos,pk=id)
    return render(request,'detalhe_prod.html',data)
def generate_report(request):
     # Cria um file-like buffer para receber os dados do PDF
     
    buffer = io.BytesIO()
    mes=request.POST.get('mes')
    ano=request.POST.get('ano')
    produtos = relatorio.objects.raw(
    "SELECT relatorio.id, relatorio.produto_id, COUNT(relatorio.produto_id) AS total "
    "FROM produto_relatorio AS relatorio, produto_produtos AS produto "
    "WHERE substr(relatorio.data_busca, 6, 2) = %s "
    "AND substr(relatorio.data_busca, 1, 4) = %s "
    "AND relatorio.produto_id = produto.id "
    "GROUP BY relatorio.produto_id ORDER BY total DESC",
    [mes, ano]
)

    # Cria o objeto PDF usando o buffer como "arquivo"
    doc = SimpleDocTemplate(buffer, pagesize=letter,topMargin=20)

    # Lista para armazenar os elementos do relatório
    elements = []
    # Obtém o estilo de amostra para os estilos de parágrafo
    styles = getSampleStyleSheet()
    logo_path = os.path.join(settings.BASE_DIR, 'accounts', 'static', 'img', 'logo.png')

    # Verifica se o arquivo da logo existe
    if os.path.exists(logo_path):
        logo = Image(logo_path, width=100, height=100)
        elements.append(logo)
    else:
        pass
    # Adiciona um título ao relatório
    title_text = "Relatório de Produtos RBC"
    title = Paragraph("<b>{}</b>".format(title_text), styles['Title'])
    elements.append(title)

    # Adiciona um parágrafo de introdução

    # Adiciona uma tabela ao relatório
    data = [['Produto', 'Quantidade']]
    
    for produto in produtos:
        produto_data = [produto.produto.nome_produto, produto.total]
        data.append(produto_data)

    column_widths = [300, 100, 100]  # Defina os valores desejados para a largura de cada coluna

    # Cria a tabela e define as larguras das colunas
    table = Table(data, colWidths=column_widths)

    table.setStyle(TableStyle([('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                               ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                               ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                               ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                               ('FONTSIZE', (0, 0), (-1, 0), 14),
                               ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                               ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                               ('ALIGN', (-1, 1), (-1, -1), 'CENTER'),
                               ]))
    elements.append(table)

    # Gera o relatório
    doc.build(elements)

    # Coloca o ponteiro do buffer no início
    buffer.seek(0)

    # Cria a resposta HTTP com o conteúdo do arquivo PDF

produto/templates/cadastro_prod.html
{% extends 'base2.html'%}
{% load static %}
{% block content %}
{% if msg %}
<div style="margin-top: 1.1%;position: relative;font-size: 14pt;font-weight: bold;" class="alert {{class}}">
   {{msg}}
</div>
{% endif %}
  <div class="formulario1">
    <form action="{% url 'produto:cad_prod' %}" method="POST" enctype="multipart/form-data" class="form">
    
    {% csrf_token %}  
      {{form.nome_produto}}<br>
      {{form.empresa}}<br>
      <!-- chamando modal -->
      <div class="preco">{{form.preco}}
        <button type="button" class="btn btn-add" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap"><img src="{% static 'img/add.png' %}" alt="add" width="20" height="20" class="align-baseline"></button>
         <br>
      </div><br>
      <label style="color: black;" class='label' for="{{ form.secao.id_for_label }}">{{ form.secao.label }}</label><br>
      {{form.secao}}<br>
      {{form.imagem}}<br>
    
    <center><button type="submit" class="botao">Cadastrar</button></center>
  </form>
  <center>
   <!--JANELA MODAL-->
   <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Adicionar Preço</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'produto:cad-preco' %}" method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            <div class="mb-3">
              {{formpreco.valor}}
              <div class="modal-footer">
                <button type="reset" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-primary">Adicionar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</center>
</div>
{% endblock %}

produto/templates/detalhe_prod.html
{% extends 'base_cliente.html' %}
{% load static %}
{% block content %}
<div class="total">
    <div class="img-top">
        <img src='{{ produto.imagem.url }}' width="200" height="200">
    </div>
    <div class="infor">
        <div class="h3 tit">{{produto.nome_produto}}</div>
        <div class="subtotal">
            {% for empresa in empresas %}
            <div class="empresa">
                <div><b>{{empresa.empresa}}</b></div>
                <div>Endereço: {{empresa.empresa.rua}}, {{empresa.empresa.bairro}}, {{empresa.empresa.cidade}}</div>
                <div style="color: red;"><b>Valor:  R$ {{empresa.preco}}</b></div>
            </div>
            {% endfor %}
        </div>
        <div></div>
        <div></div>
    </div>
</div>
{% endblock %}

produto/templates/edita_prod.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
{% if msg %}
<div style="margin-top: 1.1%;position: relative;font-size: 14pt;font-weight: bold;" class="alert {{class}}">
   {{msg}}
</div>
{% endif %}
  <div class="formulario1">
    <form action="{% url 'produto:altera-dados' id=id%}"method="POST" enctype="multipart/form-data" class="form">
    
    {% csrf_token %}  
      {{form.nome_produto}}<br>
      {{form.empresa}}
      <br>
      <!-- chamando modal -->
      <div class="preco">{{form.preco}}
        <button type="button" class="btn btn-add" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap"><img src="{% static 'img/add.png' %}" alt="add" width="20" height="20" class="align-baseline"></button>
         <br>
      </div><br>
      <label style="color: black;" class='label' for="{{ form.secao.id_for_label }}">{{ form.secao.label }}</label><br>
      {{form.secao}}<br>
      {{form.imagem}}<br>
      
      <label style="color: black;" class='label' for="{{ form.carousel.id_for_label }}">{{ form.carousel.label }}</label><br>
      {{form.carousel}}
      
    <center><button type="submit" class="botao">Cadastrar</button></center>
  </form>
  <center>
   <!--JANELA MODAL-->
   <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Adicionar Preço</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'produto:cad-preco' %}" method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            <div class="mb-3">
              {{formpreco.valor}}
              <div class="modal-footer">
                <button type="reset" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <button type="submit" class="btn btn-primary">Adicionar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</center>
</div>
{% endblock %}

produto/templates/lista_adm.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
<div class="produtos">
{% for produto in produtos %}
<!--JANELA MODAL-->
<div class="modal" tabindex="-1" role="dialog" id="modal_1">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" style="color: red;">Atenção!!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </button>
      </div>
      <div class="modal-body">
        <p>Deseja {{msn}} o produto?</p>
      </div>
      <div class="modal-footer">
        <form action="{% url 'produto:desabilita-dado' %}" method="POST">
          {% csrf_token %}  
        <input type="number" name="id" id="id" style="display: none;" value="produto.id">
        <button type="reset" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        <button type="submit" class="btn btn-danger">{{btn}}</button>
      </form>
      </div>
    </div>
  </div>
</div>
        <div class="lista2">
            <div class="img2">
                <img src='{{produto.imagem.url}}' width="100" height="100" class="imgn">
            </div>
            <div class="dados">
                <div class="h3">{{produto.nome_produto}}</div>
                <div class="sub-text">Seção: {{produto.secao}}, {{produto.empresa}}</div>
                <div class="sub-text" style="color: red;">Preço: R$ {{produto.preco}},00</div>
            </div>
            <!--Icone normal-->
            <div class="icone">
                <a href="{% url 'produto:altera-dados' id=produto.id%}">
                    <i class="fa-solid fa-square-pen fa-3x" style="color: #969696;"></i>
                </a>
                <br>
                {% if t1 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{produto.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-trash fa-3x" style="color: #ff1a1a;"></i>
                </a>
                {% endif %}
                {% if t2 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{produto.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-toggle-off fa-3x" style="color: #969696;"></i>
                </a>
                {% endif %}
            </div>
            <!--Icone Media query-->
            <div class="icone2">
                <a href="{% url 'empresa:altera-dados' id=produto.id%}">
                    <i class="fa-solid fa-square-pen fa-2x" style="color: #969696;"></i>
                </a>    
                <br>
                {% if t1 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{produto.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-trash fa-2x" style="color: #ff1a1a;"></i>
                </a>
                {% endif %}
                {% if t2 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{produto.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-toggle-off fa-2x" style="color: #969696;"></i>
                </a>
                {% endif %}
            </div>
        </div>
{% endfor %}
</div>
{% endblock %}

produto/templates/lista_produtos.html
{% extends 'base_cliente.html' %}
{% load static %}
{% block content %}
<div class="produtos">
    
    {% for produto in produtos %}
        <form action="{% url 'produto:detalhes' titulo=produto.nome_produto id=produto.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="detalha">
                <div class="lista2">
                    <div class="img2">
                        <img src='{{ produto.imagem.url }}' width="100" height="100" class="imgn">
                    </div>
                    <div class="dados">
                        <div class="h3">{{ produto.nome_produto }}</div>
                        <div class="sub-text">Seção: {{ produto.nome_secao }}</div>
                        <div class="sub-text" style="color: red;">Preço: R$ {{ produto.menor_preco }} ~ R$ {{ produto.maior_preco }}</div>
                    </div>
                </div>
            </button>
        </form>
    {% endfor %}
</div>
{% endblock %}