core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produto/', include(('produto.urls', 'produto'), namespace='produto')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('empresa/', include(('empresa.urls', 'empresa'), namespace='empresa')),
    path('pacotes/', include(('pacotes.urls', 'pacotes'), namespace='pacotes')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='empresa'
urlpatterns = [
    path('cadastro-empresa',template_cad,name='empresa_cad'),
    path('enterprise-list/',lista_empresa,name='lista-empresas'),
    path('editar-empresa/<int:id>/',alterar_dados,name='altera-dados'),
    path('editar-empresa/',alterando,name='alterando'),
    path('apagar-empresa/',upd_status,name='desabilita-dado'),
    path('empresas-desact/',empresa_desact,name='desactvated'),
    ]

empresa/models.py
from django.db import models
import sys
sys.path.append("")
from pacotes.models import Pacote

class Tipos(models.Model):
   nome_tipo = models.CharField(max_length=50,default='Selecione o Tipo')
   def __str__(self) -> str:
      return self.nome_tipo

class Estado(models.Model):
   nome_estado = models.CharField(max_length=100)
   uf = models.CharField(max_length=3)
   def __str__(self) -> str:
      return self.uf

class Cidade(models.Model):
   nome_cidade = models.CharField(max_length=100)
   uf = models.ForeignKey(Estado, on_delete=models.CASCADE)
   def __str__(self):
      return ''+str(self.nome_cidade)+'-'+str(self.uf)
   

class Empresa(models.Model):
   nome_empresa = models.CharField(max_length=100)
   tipo =  models.ForeignKey(Tipos, on_delete=models.CASCADE)
   cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)
   rua = models.CharField(max_length=255)
   bairro = models.CharField(max_length=255)
   quant_prod=models.IntegerField(default=0)
   pacote=models.ForeignKey(Pacote,on_delete=models.CASCADE, null=True,verbose_name='Selecione o Pacote')
   status=models.IntegerField(default=1)
   def __str__(self) -> str:
      return self.nome_empresa
   
   

empresa/views.py
from django.urls import reverse
from django.shortcuts import render
from .models import *
from .form import DadosForm
from django.contrib.auth.decorators import login_required
#Variáveis não comentadas já foram explicadas
# Método da página home
@login_required(login_url='accounts:login')
def template_cad(request):
    # Dicionário que para os templates
    data = {}
    # Caso tenha dados do formulário
    if request.method == 'POST':
        #Dados preenchidos pelo formulário
        form = DadosForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            data['msg'] = 'Empresa cadastrada com sucesso!'
            data['class'] = 'alert-success'

        else:
            data['msg'] = 'Formato de imagem não suportado.'
            data['class'] = 'alert-danger'
    #Caso não tenha dados
    else:
        #variável do formulário
        form = DadosForm()
    #Para se tornar mais fácil de usar
    data['form'] = form
    #Este variável ficará na tag <title>
    data['title'] = 'Cadastro de empresas'
    data['link_form'] = '123'
    #Este dado é o que fica na barra verde
    data['titulo'] = 'Cadastro Empresa'
    return render(request, '../../empresa/templates/cad_em.html', data)

#Listagem de empresas ATIVAS
@login_required(login_url='accounts:login')
def lista_empresa(request):
    data={}
    data['title']='Lista de Empresas'
    #Gambiarra de verificação presente no arquivo lista_empresa.html
    data['t1']='v'
    data['titulo']='Lista de Empresa'
    #Busca de empresas com status ativo e ordenado por nome_empresa
    data['empresas']=Empresa.objects.filter(status=1).order_by('nome_empresa')
    #Variável de mensagem da janela modal
    data['msn']='desativar'
    #Texto do botão da janela modal
    data['btn']='Desativar'
    return render(request,'../../empresa/templates/lista_empresa.html',data)
# Método que chama template de alterar dados da empresa que recebe o id
# como parâmetro
# Direciona a templates/editar_dados.html
@login_required(login_url='accounts:login')
def alterar_dados(request, id):
    data={}
    #Buscando dados atuais da empresa
    data['empresa']=Empresa.objects.get(id=id)
    #Busca por todos os tipos de empresas para a tag select
    data['pacotes']=Pacote.objects.all()
    data['tipos']=Tipos.objects.all()
    #Buscando as cidades para a tag select
    data['cidades']=Cidade.objects.all()
    data['title']='Editando Empresas'
    return render(request,'../../empresa/templates/editar_dados.html',data)
# Método que faz o update dos dados
@login_required(login_url='accounts:login')
def alterando(request):
    data={}
    # Recebendo dados do formulário
    nome=request.POST.get('nome_empresa')
    tipo=request.POST.get('tipo')
    cidade=request.POST.get('cidade')
    rua=request.POST.get('rua')
    bairro=request.POST.get('bairro')
    id=request.POST.get('id')
    data['title']='Editando Empresas'
    # Buscando os dados da empresa para filtragem
    data['empresa']=Empresa.objects.get(id=id)
    # Efetivando alterações
    emp=Empresa.objects.filter(id=id).update(nome_empresa=nome, tipo=tipo,cidade=cidade,rua=rua,bairro=bairro)
    # Verificando se alteração funcionou ou não
    if(emp):
        data['msg'] = 'Empresa editada com sucesso!'
        data['class'] = 'alert-success'
    else:
        data['class'] = 'alert-danger'
        data['msg']='Falha ao alterar dados!'
    data['tipos']=Tipos.objects.all()
    data['cidades']=Cidade.objects.all()
    data['empresa']=Empresa.objects.get(id=id)
    return render(request,'../../empresa/templates/editar_dados.html',data)
# Buscando template das empresas desativadas
@login_required(login_url='accounts:login')
def empresa_desact(request):
    data={}
    data['t2']='v'
    data['msn']='ativar'
    data['btn']='Ativar'
    data['title']='Empresas desativadas'
    data['titulo']='Empresas desativadas'
    data['empresas']=Empresa.objects.filter(status=0).order_by('nome_empresa')
    return render(request,'../../empresa/templates/lista_empresa.html',data)
# Alteração dos status das empresas
# Esta função funciona tanto pra ativar quanto para desativar empresas
@login_required(login_url='accounts:login')
def upd_status(request):
    data={}
    # Recebendo id
    id=request.POST.get('id')
    # Buscando os dados da empresa pelo id
    empresa=Empresa.objects.get(id=id)
    # Verificando qual o status recebido para fazer alterações
    # Caso seja ativado
    if(empresa.status==1):
        # Aqui temos muitas gambiarras
        data['title']='Lista de Empresas'
        data['titulo']='Lista de Empresa'
        data['t1']='v'
        data['msn']='desativar'
        data['btn']='Desativar'
        data['empresas']=Empresa.objects.filter(status=1).order_by('nome_empresa')
        emp=Empresa.objects.filter(id=id).update(status=0)
        if(emp):
            data['msg'] = 'Empresa Desativada!'
            data['class'] = 'alert-success'
        else:
            data['class'] = 'alert-danger'
            data['msg']='Algum erro aconteceu, por favor tente novamente!'
    # Caso o status seja desativado
    elif(empresa.status==0):
        data['title']='Empresas Desativadas'
        data['nome']='Voltar'
        data['titulo']='Empresas  desativadas'
        data['t2']='v'
        data['msn']='ativar'
        data['btn']='Ativar'
        data['empresas']=Empresa.objects.filter(status=0).order_by('nome_empresa')
        emp=Empresa.objects.filter(id=id).update(status=1)
        # Caso tenha sucesso ao atualizar o status
        if(emp):
            data['msg'] = 'Empresa Reativada!'
            data['class'] = 'alert-success'
        # Caso tenha algum problema
        else:
            data['class'] = 'alert-danger'
            data['msg']='Algum erro aconteceu, por favor tente novamente!'
    return render(request,'../../empresa/templates/lista_empresa.html',data)

empresa/templates/cad_em.html
{% extends 'base2.html'%}
{% block content %}
{% load static%}
{% if msg %}
<div class="alert {{class}}">
  {{msg}}
</div>
{% endif %}
<center>
<div class="formulario1">
  <form action="{% url 'empresa:empresa_cad' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="botao">Adicionar</button>
  </form>

</div>
</center>
{% endblock %}

empresa/templates/editar_dados.html
{% extends 'base2.html'%}
{% load static %}
{% block content %}
{% if msg %}
<div class="alert  {{class}}" role="alert">
    {{msg}}
</div>
{% endif %}
<center>
<div class="formulario1" style="padding-top: 50px;">
 
    <form action="{% url 'empresa:alterando' %}" method="POST" enctype="multipart/form-data" class="form form-group">
      {% csrf_token %}
      <label for="nome_empresa">Nome da Empresa:</label><br>
      <input id="nome_empresa" type="text" class="campo" name='nome_empresa' value="{{empresa.nome_empresa}}"><br>
      <label for="tipo">Tipo da Empresa:</label><br>
      <select name="tipo" id="tipo" class="campo">
        <option value="{{empresa.tipo.id}}" selected>{{empresa.tipo}}</option>
        {% for tipo in tipos %}
            <option value="{{tipo.id}}">{{tipo.nome_tipo}}</option>
        {% endfor %}
      </select><br>
      <!--<input id="tipo" type="text" class="campo" name='tipo' value="{{empresa.tipo}}">-->
      <label for="cidade">Cidade da Empresa:</label><br>
      <select name="cidade" id="cidade" class="campo">
        <option value="{{empresa.cidade.id}}" selected>{{empresa.cidade}}</option>
        {% for cidade in cidades %}
            <option value="{{cidade.id}}">{{cidade.nome_cidade}}</option>
        {% endfor %}
      </select><br>
      <label for="pacote">Cidade de Pacotes:</label><br>
      <select name="pacote" id="pacote" class="campo">
        <option value="{{empresa.pacote.id}}" selected>{{empresa.pacote}}</option>
        {% for pacote in pacotes %}
            <option value="{{pacote.id}}">{{pacote.nome}}</option>
        {% endfor %}
      </select><br>
      <!--<input id="cidade" type="text" class="campo" name='cidade' value="{{empresa.cidade}}"><br>-->
      <label for="rua">Rua da Empresa:</label><br>
      <input id="rua" type="text" class="campo" name='rua' value="{{empresa.rua}}"><br>
      <label for="bairro">Bairro da Empresa:</label><br>
      <input id="bairro" type="text" class="campo" name='bairro' value="{{empresa.bairro}}"><br>
      <input type="number" name="id" value="{{empresa.id}}" style="display: none;">

      <button type="submit" class="botao">Adicionar</button>
    </form>

</div>
</center>
{% endblock %}

empresa/templates/lista_empresa.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
<div class="geral">
{% for empresa in empresas %}
        <div class="lista">
            <div class="img">
                <img src="{% static 'img/sem_foto.png' %}" width="100" height="100">
            </div>
                    <!--JANELA MODAL-->
                    <div class="modal" tabindex="-1" role="dialog" id="modal_1">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" style="color: red;">Atenção!!</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </button>
                          </div>
                          <div class="modal-body">
                            <p>Deseja {{msn}} a empresa?</p>
                          </div>
                          <div class="modal-footer">
                            <form action="{% url 'empresa:desabilita-dado' %}" method="POST">
                              {% csrf_token %}
                            <input type="number" name="id" id="id" style="display: none;">
                            <button type="reset" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                            <button type="submit" class="btn btn-danger">{{btn}}</button>
                          </form>
                          </div>
                        </div>
                      </div>
                    </div>
                    

            <div class="dados">
                <div class="h3">{{empresa.nome_empresa}}</div>
                <div class="sub-text">Endereço: {{empresa.rua}}, {{empresa.bairro}}, {{empresa.cidade}}</div>
                <div class="sub-text" style="color: green;">Quantidade de produtos: {{empresa.quant_prod}}</div>
            </div>
            <!--Icone normal-->
            <div class="icone">
                <a href="{% url 'empresa:altera-dados' id=empresa.id%}">
                    <i class="fa-solid fa-square-pen fa-3x" style="color: #969696;"></i>
                </a>
                <br>
                {% if t1 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{empresa.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-trash fa-3x" style="color: #ff1a1a;"></i>
                </a>
                {% endif %}
                {% if t2 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{empresa.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-toggle-off fa-3x" style="color: #969696;"></i>
                </a>
                {% endif %}
            </div>
            <!--Icone Media query-->
            <div class="icone2">
                <a href="{% url 'empresa:altera-dados' id=empresa.id%}">
                    <i class="fa-solid fa-square-pen fa-2x" style="color: #969696;"></i>
                </a>    
                <br>
                {% if t1 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{empresa.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-trash fa-2x" style="color: #ff1a1a;"></i>
                </a>
                {% endif %}
                {% if t2 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{empresa.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-toggle-off fa-2x" style="color: #969696;"></i>
                </a>
                {% endif %}
                
            </div>
        </div>



{% endfor %}
</div>

{% endblock %}