core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produto/', include(('produto.urls', 'produto'), namespace='produto')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('empresa/', include(('empresa.urls', 'empresa'), namespace='empresa')),
    path('pacotes/', include(('pacotes.urls', 'pacotes'), namespace='pacotes')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='empresa'
urlpatterns = [
    path('cadastro-empresa',template_cad,name='empresa_cad'),
    path('enterprise-list/',lista_empresa,name='lista-empresas'),
    path('editar-empresa/<int:id>/',alterar_dados,name='altera-dados'),
    path('editar-empresa/',alterando,name='alterando'),
    path('apagar-empresa/',upd_status,name='desabilita-dado'),
    path('empresas-desact/',empresa_desact,name='desactvated'),
    ]

pacotes/urls.py
from .views import *
from django.urls import path
from django.contrib import admin
app_name='pacotes'
urlpatterns = [
    path('Cadastro-pacotes/',cad_pac,name='cadastro-pac'),
    path('lista-pacotes/',lista_pacotes,name='lista-pacotes'),
    path('editar-pacotes/<int:id>/',template_editar,name='template-edita'),
    path('editar-pacotes/altearando/',alterando,name='alterando'),
]

pacotes/models.py
from django.db import models
class Pacote(models.Model):
    nome=models.CharField(max_length=100, verbose_name='Nome do Pacote')
    custo=models.CharField(verbose_name='Custo do Pacote',max_length=10)
    quant_prod=models.IntegerField(verbose_name='Quantidade de Produtos')
    quant_carousel=models.IntegerField(verbose_name='Quantidade de itens de Carousel',default=0)
    descricao=models.TextField(verbose_name='Descrição do Pacote')
    img=models.ImageField(verbose_name='Animação do Pacote(.gif)',upload_to= 'pacotes/media',default='media/sem_foto.png')
    def __str__(self):
        return self.nome

pacotes/forms.py
from django import forms
from pacotes.models import Pacote

class PacoteForm(forms.ModelForm):
    class Meta:
        model=Pacote
        fields='__all__'
        widgets={
            'nome':forms.TextInput(attrs={
                'class':'campo','placeholder':'Nome do Pacote',}),
            'custo':forms.NumberInput(attrs={ 'class': 'campo'}),
            'quant_prod':forms.NumberInput(attrs={'class':'campo','placeholder':'Quantidade de Produtos'}),
            'descricao':forms.Textarea(attrs={
                'class':'campo','placeholder':'Descrição do Pacote'}),
        }

pacotes/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import PacoteForm
# Create your views here.
@login_required(login_url='accounts:login')
def cad_pac(request):
    data={}
    data['title']='Cadastro de Produtos'
    if(request.POST):
        data['form']=PacoteForm(request.POST)
        form=data['form']
        if(data['form'].is_valid()):
            produto = data['form'].save()
            if(produto):
                data['class']='alert-success'
                data['msg']='Pacote Cadastrado com Sucesso!'
        else:
            data['msg'] = 'Formulário inválido.'
            data['class'] = 'alert-danger'''
    else:
        data['form'] = PacoteForm()
        #data['form']=PacoteForm()
    data['titulo']='Cadastro Pacotes'
    return render(request,'../../pacotes/templates/cad_pacotes.html',data)
'''def lista_pacotes(request):
    data={}
    data['title']='Lista de Pacotes'
    #Gambiarra de verificação presente no arquivo lista_empresa.html
    data['t1']='v'
    data['titulo']='Lista de Pacotes'
    #Busca de empresas com status ativo e ordenado por nome_empresa
    data['pacotes']=Pacote.objects.order_by('nome')
    #Variável de mensagem da janela modal
    data['msn']='desativar'
    #Texto do botão da janela modal
    data['btn']='Desativar'
    return render(request,'../../pacotes/templates/lista_pacotes.html',data)'''
@login_required(login_url='accounts:login')
def lista_pacotes(request):
    data={}
    data['title']='Lista de Pacotes'
    #Gambiarra de verificação presente no arquivo lista_empresa.html
    data['t1']='v'
    data['titulo']='Lista de Pacotes'
    #Busca de empresas com status ativo e ordenado por nome_empresa
    data['pacotes']=Pacote.objects.order_by('nome')
    #Variável de mensagem da janela modal
    data['msn']='desativar'
    #Texto do botão da janela modal
    data['btn']='Desativar'
    return render(request,'../../pacotes/templates/lista_pacotes.html',data)
@login_required(login_url='accounts:login')
def template_editar(request,id):
    data={}
    #Buscando dados atuais da empresa
    data['pacote']=Pacote.objects.get(id=id)
    data['title']='Editando Pacotes '
    return render(request,'../../pacotes/templates/editar_pacotes.html',data)
@login_required(login_url='accounts:login')
def alterando(request):
    data={}
    # Recebendo dados do formulário
    nome=request.POST.get('nome')
    custo=request.POST.get('custo')
    quant=request.POST.get('quant')
    desc=request.POST.get('desc')
    img=request.POST.get('img')
    id=request.POST.get('id')
    data['title']='Editando Pacotes'
    # Buscando os dados da empresa para filtragem
    data['pacote']=Pacote.objects.get(id=id)
    # Efetivando alterações
    emp=Pacote.objects.filter(id=id).update(nome=nome, custo=custo,quant_prod=quant,descricao=desc,img=img)
    # Verificando se alteração funcionou ou não
    if(emp):
        data['msg'] = 'Pacote editado com sucesso!'
        data['class'] = 'alert-success'
    else:
        data['class'] = 'alert-danger'
        data['msg']='Falha ao alterar dados!'
    data['pacote']=Pacote.objects.get(id=id)
    return render(request,'../../pacotes/templates/editar_pacotes.html',data)

pacotes/templates/cad_pacotes.html
{% extends 'base2.html'%}
{% load static %}
{% block content %}
{% if msg %}
<div style="margin-top: 1.1%;position: relative;font-size: 14pt;font-weight: bold;" class="alert {{class}}">
   {{msg}}
</div>
{% endif %}
  <div class="formulario1">
    <form action="{% url 'pacotes:cadastro-pac' %}" method="POST" enctype="multipart/form-data" class="form">
    
    {% csrf_token %}  
    <label style="color: black;" class='label' for="{{ form.nome.id_for_label }}">{{ form.nome.label }}</label><br>
      {{form.nome}}<br>
      <label style="color: black;" class='label' for="{{ form.custo.id_for_label }}">{{ form.custo.label }}</label><br>
      {{form.custo}}<br>
      <label style="color: black;" class='label' for="{{ form.quant_prod.id_for_label }}">{{ form.quant_prod.label }}</label><br>
      {{form.quant_prod}}
      <br>
      <label style="color: black;" class='label' for="{{ form.descricao.id_for_label }}">{{ form.descricao.label }}</label><br>
      {{form.descricao}}<br>
    
    <center><button type="submit" class="botao">Cadastrar</button></center>
  </form>
  </div>
</div>
{% endblock %}

pacotes/templates/editar_pacotes.html
{% extends 'base2.html'%}
{% load static %}
{% block content %}
{% if msg %}
<div class="alert  {{class}}" role="alert">
    {{msg}}
</div>
{% endif %}
<center>
<div class="formulario1">
 
    <form action="{% url 'pacotes:alterando' %}" method="POST" enctype="multipart/form-data" class="form form-group">
      {% csrf_token %}
      <label for="nome">Nome do Pacote:</label><br>
      <input id="nome" type="text" class="campo" name='nome' value="{{pacote.nome}}"><br>
      <!--<input id="tipo" type="text" class="campo" name='tipo' value="{{empresa.tipo}}">-->
      <label for="quant">Quantidade de produtos:</label><br>
      <input id="quant" type="number" class="campo" name='quant' value="{{pacote.quant_prod}}"><br>
      <!--<input id="cidade" type="text" class="campo" name='cidade' value="{{empresa.cidade}}"><br>-->
      <label for="custo">Custo:</label><br>
      <input id="custo" type="text" class="campo" name='custo' value="{{pacote.custo}}"><br>
      <label for="desc">Descrição:</label><br>
      <input id="desc" type="text" class="campo" name='desc' value="{{pacote.descricao}}"><br>
      <label for="img">
      <input id="img" type="file" class="campo" name='img'><br>
      <input type="number" name="id" value="{{pacote.id}}" style="display: none;">

      <button type="submit" class="botao">Adicionar</button>
    </form>

</div>
</center>
{% endblock %}

pacotes/templates/lista_pacotes.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
<<<<<<< HEAD
=======
<div class="geral">
{% for pacote in pacotes %}
        <div class="lista_pac">
          {% if pacote.img %}
            <div class="img">
                <img src="{{pacote.img.url}}" width="100" height="100">
            </div>
          {% endif %}
          {% if not pacote.img %}
          <div class="img">
            <img src="{% static 'img/sem_foto.png' %}" width="100" height="100">
          </div>
          {% endif %}

                    <!--JANELA MODAL-->
                    <div class="modal" tabindex="-1" role="dialog" id="modal_1">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" style="color: red;">Atenção!!</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </button>
                          </div>
                          <div class="modal-body">
                            <p>Deseja {{msn}} o pacote?</p>
                          </div>
                          <div class="modal-footer">
                            <form action="{% url 'empresa:desabilita-dado' %}" method="POST">
                              {% csrf_token %}  
                            <input type="number" name="id" id="id" style="display: none;">
                            <button type="reset" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                            <button type="submit" class="btn btn-danger">{{btn}}</button>
                          </form>
                          </div>
                        </div>
                      </div>
                    </div>
                    

            <div class="dados">
                <div class="h3">{{pacote.nome}}</div>
                <div class="sub-text">Quandidade de Produtos: {{pacote.quant_prod}}</div>
                <div class="sub-text" style="color: green;">Valor do Pacote: {{pacote.custo}}</div>
                <div class="sub-text">Descrição: {{pacote.descricao}}</div>
            </div>
            <!--Icone normal-->
            <div class="icone">
                <a href="{% url 'pacotes:template-edita' id=pacote.id %}">
                    <i class="fa-solid fa-square-pen fa-3x" style="color: #969696;"></i>
                </a>
                <br>
                {% if t1 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{pacote.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                <!--  <i class="fa-solid fa-trash fa-3x" style="color: #ff1a1a;"></i>-->
                </a>
                {% endif %}
                {% if t2 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{empresa.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-toggle-off fa-3x" style="color: #969696;"></i>
                </a>
                {% endif %}
            </div>
            <!--Icone Media query-->
            <div class="icone2">
                <a href="{% url 'empresa:altera-dados' id=pacote.id%}">
                    <i class="fa-solid fa-square-pen fa-2x" style="color: #969696;"></i>
                </a>    
                <br>
                {% if t1 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{pacote.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                <!--  <i class="fa-solid fa-trash fa-2x" style="color: #ff1a1a;"></i>-->
                </a>
                {% endif %}
                {% if t2 %}
                <a type="button" class="botao_modal" data-bs-toggle="modal" onclick="setaDadosModal('{{pacote.id}}')" data-bs-target="#modal_1" data-bs-whatever="@getbootstrap">
                  <i class="fa-solid fa-toggle-off fa-2x" style="color: #969696;"></i>
                </a>
                {% endif %}
                
            </div>
        </div>



{% endfor %}
</div>
>>>>>>> 5faab1065d0c287f175cd1f03d3192e5a17bcd3c

{% endblock %}