accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    # ...
    path('bla/', inicio, name='index'),
    path('cadastra-adm/', cadastro, name='cadastro_template'),
    path('', home, name='home'),
    path('contato/', contato, name='contato'),
    path('sobre/', sobre, name='sobre'),
    path('cadastrando/', cadastrando, name='cadastrando'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('produto/', include(('produto.urls', 'produto'), namespace='produto')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('empresa/', include(('empresa.urls', 'empresa'), namespace='empresa')),
    path('pacotes/', include(('pacotes.urls', 'pacotes'), namespace='pacotes')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name='empresa'
urlpatterns = [
    path('cadastro-empresa',template_cad,name='empresa_cad'),
    path('enterprise-list/',lista_empresa,name='lista-empresas'),
    path('editar-empresa/<int:id>/',alterar_dados,name='altera-dados'),
    path('editar-empresa/',alterando,name='alterando'),
    path('apagar-empresa/',upd_status,name='desabilita-dado'),
    path('empresas-desact/',empresa_desact,name='desactvated'),
    ]

pacotes/urls.py
from .views import *
from django.urls import path
from django.contrib import admin
app_name='pacotes'
urlpatterns = [
    path('Cadastro-pacotes/',cad_pac,name='cadastro-pac'),
    path('lista-pacotes/',lista_pacotes,name='lista-pacotes'),
    path('editar-pacotes/<int:id>/',template_editar,name='template-edita'),
    path('editar-pacotes/altearando/',alterando,name='alterando'),
]

produto/urls.py
from .views import *
from django.contrib import admin
from django.urls import path
app_name='produto'
urlpatterns = [
    path('cadastro-produto/',cad_prod,name='cad_prod'),
    path('cadastro-preco/',cad_preco,name='cad-preco'),
    path('search-product/',busca_prod,name='busca-produto'),
    path('secoes/<str:v>/',secoes,name='secoes'),
    path('lista-produtos/',listagem,name='lista-produtos'),
    path('edita-prod/<int:id>/',template_altera,name='altera-dados'),
    path('desabilitado/ ',upd_status,name='desabilita-dado'),
    path('detalhes/<str:titulo>/<int:id>/',detalhes,name='detalhes'),
    path('relatorio/',generate_report, name='relatorio'),
    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
class administrador(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.usuario.first_name

accounts/views.py
from django.shortcuts import render,redirect
from .models import *
import sys
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,logout, login as auth_login
sys.path.append("")
from produto.models import *
# Método de login page
def login_view(request):
    data = {}
    data['link_cad']="{% url 'accounts:cadastro_template'%}"
    data['nome']='Login'
    data['titulo']='Login'
    data['title']='Login'
    if request.POST:
        email = request.POST.get('email')
        senha = request.POST.get('senha')
        usuario_test=User.objects.filter(email=email)
        if usuario_test:
            usuario=User.objects.get(email=email)
            user = authenticate(request, username=usuario.username, password=senha)
            if user is not None:
                #print(jogador.saldo)
                auth_login(request, user)
                return redirect('accounts:index')
            else:
                data['msg'] = 'Senha inválida!'
                data['class'] = 'alert-danger'
        elif(not usuario_test):
            data['msg'] = 'E-mail inválido!'
            data['class'] = 'alert-danger'
    return render(request,'../../accounts/templates/login.html',data)
@login_required(login_url='accounts:login')
def logout_view(request):
    logout(request)
    return redirect('accounts:login')
@login_required(login_url='accounts:login')
def inicio(request):
    data = {}
    data['link_cad'] = 'accounts:cadastro_template'
    data['nome'] = 'Cadastrar ADM'
    data['titulo'] = 'Página do ADM'
    data['title'] = 'ADM Principal'
    
    data['res'] = relatorio.objects.raw(
        """
    SELECT relatorio.id, strftime('%m', relatorio.data_busca) AS mes, 
           CASE strftime('%m', relatorio.data_busca)
               WHEN '01' THEN 'Janeiro'
               WHEN '02' THEN 'Fevereiro'
               WHEN '03' THEN 'Março'
               WHEN '04' THEN 'Abril'
               WHEN '05' THEN 'Maio'
               WHEN '06' THEN 'Junho'
               WHEN '07' THEN 'Julho'
               WHEN '08' THEN 'Agosto'
               WHEN '09' THEN 'Setembro'
               WHEN '10' THEN 'Outubro'
               WHEN '11' THEN 'Novembro'
               WHEN '12' THEN 'Dezembro'
               ELSE 'Mês inválido'
           END AS mes2,
           relatorio.produto_id, COUNT(relatorio.produto_id) AS total
    FROM produto_relatorio AS relatorio
    GROUP BY mes;
"""
    )
    data['res2'] = relatorio.objects.raw(
        """
    SELECT relatorio.id, strftime('%Y', relatorio.data_busca) AS ano, 
           relatorio.produto_id
    FROM produto_relatorio AS relatorio
    GROUP BY ano;
"""
    )
    
    return render(request, 'inicio.html', data)

@login_required(login_url='accounts:login')
def cadastro(request):
    data={}
    data['title']='Cadastro ADM'
    data['link_form']="{% url 'accounts:index'%}"
    data['nome']='Voltar'
    data['titulo']='Cadastro ADM'
    return render(request,'../../accounts/templates/cadastro.html',data)
@login_required(login_url='accounts:login')
def cadastrando(request):
    titulo='Cadastro Administrador'
    data={}
    try:
        usuario_aux = User.objects.get(username=request.POST['user'])
        usuario_aux2= User.objects.filter(password=request.POST['senha'])

        if usuario_aux or usuario_aux2:
            data['msg'] = 'Usuario ou Senha já existem!'
            data['class'] = 'alert-danger'
    except User.DoesNotExist:
        print('senha: ',request.POST.get('email'))

        if request.POST.get('senha')==request.POST.get('senha_repeat'):
            user = User.objects.create_user(username=request.POST.get('user'),email=request.POST.get('email'), first_name=request.POST.get('nome'), password=request.POST.get('senha'))
            query_user=User.objects.get(id=user.id)
            usu= administrador.objects.create(usuario=query_user)
            user.save()
            data['msg'] = 'Usuário cadastrado com sucesso! Faça Login.'
            data['class'] = 'alert-success'''
        else:
            data['msg'] = 'Senhas incompatíveis.'
            data['class'] = 'alert-danger'''
    data['title']='Cadastro Administrador'
    data['link_form']="{% url 'accounts:index'%}"
    data['nome']='Voltar'
    data['titulo']='Cadastro Administrador'
    return render(request,'../../accounts/templates/cadastro.html',data)

def home(request):
    data={}
    data['nome']='Home'
    data['titulo']='Home'
    data['title']='Home'
    data['prods']=produtos.objects.all()
    return render(request,'../../accounts/templates/home.html',data)


def contato(request):
    data={}
    data['nome']='Contato'
    data['titulo']='Contato'
    data['title']='Contato'
    return render(request,'../../accounts/templates/contato.html',data)

def sobre(request):
    data={}
    data['nome']='Sobre'
    data['titulo']='Sobre'
    data['title']='Sobre'
    return render(request,'../../accounts/templates/sobre.html',data)

accounts/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Arquivos CSS-->
    <link rel="icon" href="{% static 'img/logo.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilo2.css' %}">
    <!--Arquivo JS-->
    <script src='{% static "js/bootstrap.bundle.js" %}'></script>
    <!--Font awesome-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://kit.fontawesome.com/c65d405071.js" crossorigin="anonymous"></script>
    <title>{{title}}</title>
</head>
<body>
    <!--Cabeçalho superior-->
    <div class="header">
        
        <div class="sup">
            <a href="{% url 'accounts:index'%}"><div class="logo"><img src="{% static 'img/logo.png' %}" alt="Logo"></div></a>
            {% if request.user.is_authenticated %}
            <div class="text">Área do Administrador</div>
            <!--Menu normal-->
            
            <div class="menu">
                <div class="item"><a href="{% url 'empresa:lista-empresas'%}">Empresas</a></div>
                <div class="item"><a href="{% url 'pacotes:lista-pacotes' %}">Pacotes</a></div>
                <div class="item"><a href="{% url 'produto:lista-produtos'%}">Produtos</a></div>
                <div class="item"><a href="{% url 'accounts:cadastro_template'%}">Cadastro ADM</a></div>
                <div class="item" id="op_av">
                    <a style="color:black;" class=" dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        Opções Avançadas
                    </a>
                    <ul class="dropdown-menu">
                        <a id="relatorio-link" class="dropdown-item" href="#">Relatório de buscas</a>
                        <!--<li><a class="dropdown-item" href="{% url 'produto:relatorio' %}">Relatório de buscas</a></li>-->
                        <li><a class="dropdown-item" href="{% url 'empresa:desactvated' %}">Ativar empresas</a></li>
                        <li><a class="dropdown-item" href="#">Ativar produtos</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sair</a></li>
                    </ul>
                </div>
            </div>
            <!--Fechamento menu normal-->

            <!--MENU DO MEDIA QUERY-->
            <div class="menu_resp">
                <div id="mySidebar" class="sidebar">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    <div class="item"><a href="{% url 'accounts:index'%}">HOME</a></div>
                    <div class="item"><a href="{% url 'empresa:lista-empresas'%}">Empresas</a></div>
                    <div class="item"><a href="{% url 'pacotes:lista-pacotes' %}">Pacotes</a></div>
                    <div class="item"><a href="{% url 'produto:lista-produtos'%}">Produtos</a></div>
                    
                    <div class="item">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" id="opc">
                            Opções Avançadas
                        </a>
                        <ul class="dropdown-menu">
                          <li><a id="relatorio-link" class="dropdown-item" href="#">Relatório de buscas</a></li>
                          <li><a id="opc1" class="dropdown-item" href="{% url 'empresa:desactvated' %}">Ativar empresas</a></li>
                          <div class="item"><a id="opc1" href="{% url 'accounts:cadastro_template'%}">Cadastro ADM</a></div>
                        </ul>
                      </li>
                    </div>
                </div>
                <div id="main">
                    <button class="openbtn" onclick="openNav()">&#9776;</button>
                </div>
                  
            </div>
            <!--FECHAMENTO DA DIV MEDIA QUERY-->
            {% endif %}
        </div>
        
        <!--Barra verde-->
        <div class="title"> 
    
            {{titulo}}

        </div>
    </div>
    {% block content %}

    {% endblock %}
    <!--
        Modal de relatório
    -->
<div class="modal" id="relatorioModal" tabindex="-1" role="dialog" aria-labelledby="relatorioModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="relatorioModalLabel">Relatório de Buscas</h5>
                <button type="button" class="btn" data-dismiss="modal" aria-label="Close" id="fecharModal" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Conteúdo do relatório de buscas -->
                <!-- Você pode adicionar aqui a tabela ou qualquer outro conteúdo do relatório -->
                <p>Selecione o mês e o ano:</p>
                <form action="{% url 'produto:relatorio' %}" method="POST" class="">
                    {% csrf_token %}
                    <select name="mes" id="mes" class="form-select">
                        {% for item in res %}
                            <option value="{{ item.mes}}">{{ item.mes2 }}</option>
                        {% endfor %}
                    </select><br>
                    <select name="ano" id="ano" class="form-select">
                        {% for item in res2 %}
                            <option value="{{ item.ano}}">{{ item.ano }}</option>
                        {% endfor %}
                    </select>
                    
               

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Enviar</button>
                <button type="button" class="btn btn-secondary" id="fecharModal2" data-dismiss="modal">Fechar</button>

            </div>
        </form>
        </div>
    </div>
</div>


    
</body>
<script>
/* Código JS menu media query */
function setaDadosModal(valor) {
    document.getElementById('id').value = valor;
}
/* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
function openNav() {
  document.getElementById("mySidebar").style.width = "250px";
  document.getElementById("main").style.marginRight = "250px";
  document.getElementById("main").style.display = "none";

}

/* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
function closeNav() {
  document.getElementById("mySidebar").style.width = "0";
  document.getElementById("main").style.marginRight = "0";
  document.getElementById("main").style.display = "flex";
}
$('#modal_1').on('shown.bs.modal', function () {
    var recipientId    = button.data('id');
    modal.find('#id').val(recipientId)
  $('#myInput').trigger('focus')
})

</script>
<script>
    $(document).ready(function() {
    $('#relatorio-link').click(function() {
        $('#relatorioModal').modal('show');
    });

    $('#fecharModal').click(function() {
        $('#relatorioModal').modal('hide');
    });
    $('#fecharModal2').click(function() {
        $('#relatorioModal').modal('hide');
    });
    $('#relatorioModal').on('hidden.bs.modal', function (e) {
        $(this).find('form')[0].reset(); // Limpa os campos do formulário dentro da modal
    });
});


</script>
</html>

accounts/templates/base_adm.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src='{% static "js/bootstrap.bundle.js" %}'></script>
  <title>{{title}}</title>
</head>
<body>
  <div class="container-fluid cabecalho">
    <div class="menu">
      <nav class="navbar bg-body-tertiary fixed-top bg-ligth" style="height: 5rem;">
        <div class="container-fluid">
          <div class="navbar-brand logo col-md-0 col-lg-0 col-sm-0"><a href="{% url 'accounts:index'%}"><img src="{% static 'img/logo.png' %}" alt="Logo" width="55" height="65" class="logo"></a></div>
          <div class="adm h1 col-md-6 text-center"><h1>Área do Administrador</h1></div> 
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header" style="background-color: #29B9B0;font-family: Arial, Helvetica, sans-serif;">
              <h5 class="offcanvas-title w-100 h-100" style="margin-left: -1.6vw;padding-left: 1.5vw;" id="offcanvasNavbarLabel">RBC</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
              <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                <li class="nav-item">
                  <a href="{% url 'empresa:lista-empresas'%}">Empresas</a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'pacotes:lista-pacotes' %}">Pacotes</a>
                </li>
                  <li class="nav-item">
                    <a href="{% url 'accounts:cadastro_template'%}">Cadastro ADM</a>
                  </li>
                  
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Opções Avançadas
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Relatório de buscas</a></li>
                    <li><a class="dropdown-item" href="#">Ativar/Destaviar empresas</a></li>
                    <li>
                      <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="#">Alterar dados de empresas</a></li>
                  </ul>
                </li>
              </ul>
              <form class="d-flex mt-3" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </div>
      
      </nav>
</div>
  <div class="header container-fluid w-100 justify-content-md-center">
    <h3>{{titulo}}</h3>
  </div>
</div>
  {% block content %}

  {% endblock %}
</body>
</html>
  <!--<main class="main">
    <div class="container-fluid">
    <div class="row">
    <div class='logo col-md-6 bg-dark'><img src="{% static 'img/logo.jpg' %}" alt="Logo" width="105" height="100" class="logo"></div>
    <div class="rbc col-md-4">RBC</div>
    <div class="adm h1 col-md-6"><h1>Área do Administrador</h1></div>
    <div class="empresas h3 col-md-6"><a href="{% url 'empresa:lista-empresas'%}"><h3>Empresas</h3></a></div>
    <div class="pacotes h3 col-md-6"><a href="{% url 'pacotes:lista-pacotes' %}"><h3>Pacotes</h3></a></div>
    {% if link_cad %}
    <div class="voltar col-sm-6 col-md-4 col-lg-3"><a href="{% url 'accounts:cadastro_template'%}"><h3>{{nome}}</h3></a></div>
    {% endif %}
    {% if link_form%}
    <div class="voltar col-sm-6 col-md-4 col-lg-3"><a href="{% url 'accounts:index'%}"><h3>{{nome}}</h3></a></div>
    {% endif %}
    </div>
  </div>
  </main>
<div class="header container-fluid w-100 justify-content-md-center">
  <h3>{{titulo}}</h3>
</body>
</html>-->

accounts/templates/base_cliente.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Arquivos CSS-->
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilo2.css' %}">
    <!--Arquivo JS-->
    <script src='{% static "accounts/static/js/bootstrap.bundle.js" %}'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
    <!--ícone -->
    <link rel="icon" href="{% static 'img/logo.png' %}">


    
    
    <!--Font awesome-->
    <script src="https://kit.fontawesome.com/c65d405071.js" crossorigin="anonymous"></script>
    <title>{{title}}</title>
</head>
<body>
    <!--Cabeçalho superior-->
    <div class="header">
        <div class="sup">
            <a href="{% url 'accounts:home'%}"><div class="logo"><img src="{% static 'img/logo.png' %}" alt="Logo"></div></a>
            <div class="text">Bem-Vindo</div>
            <!--Menu normal-->
            <div class="menu">
                <div class="item"><a href="{% url 'accounts:home'%}">Home</a></div>
                <div class="item"><a href="{% url 'accounts:contato'%}">Contato</a></div>
                <div class="item"><a href="{% url 'accounts:sobre'%}">Sobre</a></div>
            </div>

            <!--Fechamento menu normal-->

            <!--MENU DO MEDIA QUERY-->
            <div class="menu_resp">
                <div id="mySidebar" class="sidebar">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                    <div class="item"><a href="{% url 'accounts:home'%}">Home</a></div>
                    <div class="item"><a href="{% url 'accounts:contato'%}">Contato</a></div>
                    <div class="item"><a href="{% url 'accounts:sobre'%}">Sobre</a></div>
                </div>
                <div id="main">
                    <button class="openbtn" onclick="openNav()">&#9776;</button>
                </div>
                  
            </div>
            <!--FECHAMENTO DA DIV MEDIA QUERY-->
        </div>
        <!--Barra verde-->
        <div class="title2" style="color: rgb(255, 255, 255);padding-left: 3%;"> 
    
            <div class="title2">
                <div class="busca ">
                <center>
                    <form action="{% url 'produto:busca-produto' %}" method="POST" class="formulario">
                        {% csrf_token %}
                        <input class="campo-search" type="text" name="search" id="busca" placeholder="Faça uma busca pelos produtos desejados">
                        <button type="submit" class="botao2">
                            <i class="fa-solid fa-magnifying-glass" style="color: #19877E;"></i>
                        </button>
                    </form>
                </center>   
                </div>
            </div>
        </div>
    </div>
    {% block content %}

    {% endblock %}
</body>
<script src="{% static 'js/jquery.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script>

    // Capturando o formulário e o campo de entrada
    const searchForm = document.getElementById('search-form');
    const searchInput = document.getElementById('search-input');
    const searchResults = document.getElementById('search-results');

    // Função para processar a pesquisa
    function processSearch(event) {
        event.preventDefault(); // Impedindo o envio do formulário

        const query = searchInput.value; // Obtendo o valor da pesquisa

        // Aqui você pode fazer o processamento da pesquisa com base na consulta 'query'
        // Exemplo: você pode enviar uma requisição AJAX para buscar os resultados da pesquisa

        // Limpando os resultados anteriores
        searchResults.innerHTML = '';

        // Exemplo: adicionando resultados de teste
        const resultados = [
          
        ];

        if (resultados.length === 0) {
            const noResultsElement = document.createElement('p');
            noResultsElement.textContent = 'Nenhum resultado encontrado.';
            searchResults.appendChild(noResultsElement);
        } else {
            resultados.forEach(resultado => {
                const resultElement = document.createElement('p');
                resultElement.textContent = resultado;
                searchResults.appendChild(resultElement);
            });
        }
    }

    // Adicionando o evento submit ao formulário
    searchForm.addEventListener('submit', processSearch);
</script>
</body>
<script>
/* Set the width of the sidebar to 250px and the left margin of the page content to 250px */
function openNav() {
document.getElementById("mySidebar").style.width = "250px";
document.getElementById("main").style.marginRight = "250px";
document.getElementById("main").style.display = "none";

}

/* Set the width of the sidebar to 0 and the left margin of the page content to 0 */
function closeNav() {
document.getElementById("mySidebar").style.width = "0";
document.getElementById("main").style.marginRight = "0";
document.getElementById("main").style.display = "flex";
}
</script>
</html>

accounts/templates/cadastro.html
{% extends 'base2.html'%}
{% block content %}
{% if msg %}
<div class="alert {{class}}">
   {{msg}}
</div>
{% endif %}
<div class="formulario1">

  <form action="{% url 'accounts:cadastrando' %}" method="POST" enctype="multipart/form-data" class="form">
    {% csrf_token %}  
    <input type="text" name="user" id="nome" class="campo" placeholder="Usuário"required><br>
    <input type="text" name="nome" id="nome" class="campo" placeholder="Nome"required><br>
    <input type='text' name="email" id="nome" class="campo" placeholder="E-mail"required><br>
    <input type="password"name="senha" id="nome" class="campo" placeholder="Senha"required><br>
    <input type="password" name="senha_repeat" id="nome" class="campo" placeholder="Repetir Senha" required><br>
    <center><button type="submit" class="botao">Cadastrar</button></center>
  </form>
</div>
{% endblock %}

accounts/templates/inicio.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
<div class="secao">
    <a href="{% url 'empresa:empresa_cad' %}" class="borda">
        <div class="op">
            <img src="{% static 'img/empresas.ico'%}" alt="empresas">Cadastro de empresas
        </div>
    </a>
    
  <a href="{% url 'produto:cad_prod' %}" class="borda">
      <div class="op">
          <img src="{% static 'img/produtos.ico'%}" alt="empresas">Cadastro de produtos
      </div>
  </a>
  <a href="{% url 'pacotes:cadastro-pac' %}" class="borda">
    <div class="op">
        <img src="{% static 'img/pacotes.ico'%}" alt="empresas">Cadastro de pacotes
    </div>
</a>
</div>
{% endblock %}

accounts/templates/login.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
<div class="total2">
  <div class="image">
    <img src="{% static 'img/logo.png' %}" width="200" height="200">
  </div>
  <div class="borda2">
  </div>
  <div class="form-login">
      <h1>Login</h1>
      {% if msg %}
        <div class="alert {{class}}">
          {{msg}}
        </div>
      {% endif %}
      <form method="POST" class="formzin">
        {% csrf_token %}
        <div class="inputs">
          <label for="email" class="label">Email:</label>
          <input class="campos" type="email" id="email" name="email" placeholder="E-mail" required><br>
          <label for="senha" class="label">Senha:</label>
          <input class="campos" type="password" id="senha" name="senha" placeholder="Senha" required><br>
          <input type="submit" value="Login" class="campos2">
        </div>
      </form>
  </div>
</div>
{% endblock %}

accounts/templates/sobre.html
{% extends 'base_cliente.html' %}
{% load static %}
{% block content %}
<div class="texto-sobre">
    <div class="esquerda">
        <div> Quem somos nós?</div><br>
        <div class="div-img"><img src="{% static 'img/logo.png' %}" alt="Image" class="img-sobre"></div>
    </div>
    <div class="space">

    </div>
    <div class="direita">
        
            Somos uma empresa de desenvolvimento e 
            divulgação de produtos com o objetivo de interligar o 
            estabelecimento e seus clientes buscando benefícios a ambos, 
            contribuindo assim para que ambos tenham uma ótima experiência!
        
    </div>
</div>
                
{% endblock %}